from collections.abc import Awaitable

class NativeCompletion:
    @property
    def operation_id(self) -> int: ...
    def wait(self) -> Awaitable[str]: ...

class NativeMqttClient:
    def __init__(self, configuration: str) -> None: ...
    def connect(self) -> Awaitable[str]: ...
    def enqueue_publish(self, topic: str, payload: bytes, options: str | None) -> Awaitable[str]: ...
    def publish(
        self, topic: str, payload: bytes, options: str | None
    ) -> Awaitable[tuple[str, NativeCompletion | None]]: ...
    def subscribe(self, filters: str, options: str | None) -> Awaitable[tuple[str, NativeCompletion | None]]: ...
    def unsubscribe(self, filters: str, options: str | None) -> Awaitable[tuple[str, NativeCompletion | None]]: ...
    def acknowledge(self, acknowledgement_id: int) -> Awaitable[tuple[str, NativeCompletion | None]]: ...
    def next_event(self) -> Awaitable[str]: ...
    def diagnostics(self) -> Awaitable[str]: ...
    def close(self, timeout_ms: int) -> Awaitable[str]: ...
    def close_now(self, timeout_ms: int) -> Awaitable[str]: ...
    def abandon(self) -> None: ...
    def cleanup(self, timeout_ms: int) -> None: ...
