[package]
name = "benchmarks"
version = "0.4.0"
publish = false
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
alloc-metrics = []
profiling = ["dep:pprof"]
url = ["rumqttc_v4/url", "rumqttc_v5/url"]
websocket = ["rumqttc_v4/websocket", "rumqttc_v5/websocket"]

[dependencies]
bytes = "1"
anyhow = "1"
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
itoa = "1"
mqtt5 = { version = "=0.38.1", default-features = false }
rumqttc_v4 = { package = "rumqttc-v4-next", path = "../rumqttc-v4" }
rumqttc_v5 = { package = "rumqttc-v5-next", path = "../rumqttc-v5" }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
tokio = { version = "1", features = ["full"] }
url_parser = { package = "url", version = "2" }
rand = "0.10"
libc = "0.2"

[target.'cfg(unix)'.dependencies]
pprof = { version = "0.15", features = ["prost-codec"], optional = true }

[[bin]]
name = "rumqtt-bench"
path = "src/main.rs"

[[bin]]
name = "rumqtt-bench-router"
path = "src/bin/rumqtt-bench-router.rs"

[[bin]]
name = "rumqtt-library-bench"
path = "src/bin/rumqtt-library-bench.rs"
